name: Hub Integration
author: hub
description: Run Hub Integration
inputs:
  github-token:
    description: 'github-token'
    required: true
  actions:
    description: 'actions'
    required: true
    default:  ''
outputs:
  result: 
    description: 'Random number'
    value: '0'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: baseline-test
      id: baseline-test
      if: ${{ inputs.actions === 'all' || inputs.actions === 'baseline-test'}}
      uses: jina-ai/hub-integration/.github/actions/baseline-test@master
      with: 
        python-version: '3.7'
        github-token: ${{ inputs.github-token }}
    - name: get baseline-test result
      if: ${{ inputs.actions === 'all' || inputs.actions === 'baseline-test'}}
      run: echo ${{ steps.baseline-test.outputs.result }}
      shell: bash
    - name: docker-source-combine
      if: ${{ inputs.actions === 'all' || inputs.actions === 'docker-source-combine'}}
      id: docker-source-combine
      uses: jina-ai/hub-integration/.github/actions/docker-source-combine@master
      with: 
        python-version: '3.7'
        node-version: '16.x'
        case-path: 'success/case1'
        node_env: 'testing'
        jina_hubble_registry: 'http://localhost:3000'
        github-token: ${{ inputs.github-token }}
    - name: get docker-source-combine result 
      if: ${{ inputs.actions === 'all' || inputs.actions === 'docker-source-combine'}}
      run: echo ${{ steps.docker-source-combine.outputs.result }}
      shell: bash
        