name: 'docker-source-combine'
description: 'docker source combine'
inputs:
  python_version: 
    description: python_version
    default: '3.7'
    required: true
  jina_ref: 
    description: 'use branch ref'
    default: 'refs/heads/master'
    required: false
  jin_dev_bot: 
    description: 'use token pull jina-ai/jina'
    required: true
outputs:
  result:
    description: 'result'
    value: ${{ steps.finally.outputs.result }}
runs:
  using: composite
  steps:
      - uses:  actions/checkout@v2
      - name: Use Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python_version: ${{ inputs.python_version }}

      - name: Clone latest jina code
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          token: ${{ inputs.jin_dev_bot }}
          ref: ${{ inputs.jina_ref }}
          path: jina
      
      - name: pip install jina
        working-directory: jina
        run: pip install -e '.[standard]'
        shell: bash

      - run: docker version
        shell: bash

      - run: python ${{ github.action_path }}/executor.py
        shell: bash

      - name: finally
        id: finally
        run: echo "::set-output name=result::0"
        shell: bash