name: Docker source combine usage test

on:
  schedule:
    # Every day 11:40 Shanghai time
    - cron:  '41 3 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  usage-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone latest jina code
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/heads/master
          path: jina
      
      - name: pip install jina
        working-directory: jina
        run: pip install -e '.[standard]'

      - run: docker version

      - run: python docker-source-combine.py
        

