name: hub integration
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      actions:
        description: "You may run tests selectively. Options [ all, sanity_check, regression_test ]"
        required: false
        default: "regression_test"
        type: string
      hubble_ref:
        description: "hubble_ref"
        required: false
        default: "refs/heads/master"
        type: string
      jina_ref:
        description: "jina_ref"
        required: false
        default: "refs/heads/master"
        type: string
      node_version:
        description: "node_version"
        required: false
        default: "lts/*"
        type: string
      python_version:
        description: "python_version"
        required: false
        default: "3.7"
        type: string
    secrets:
      extended_github_token:
        description: "Your GitHub token. It's used for pulling hubble and jina repo"
        required: true
      jina_auth_token:
        description: "Your jina auth token. It's used for running sanity_check in jina production environment"
        required: true
    outputs:
      sanity_check_result:
        description: "Result of sanity check"
        value: ${{ jobs.sanity_check.outputs.result }}
      regression_test_result:
        description: "Result of regression test"
        value: ${{ jobs.regression_test.outputs.result }}
jobs:
  sanity_check:
    if: ${{ inputs.actions == 'all' ||  contains(inputs.actions, 'sanity_check') }}
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.sanity_check.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: sanity_check
        id: sanity_heck
        uses: jina-ai/hub-integration/actions/sanity-check@main
        with:
          jina_auth_token: ${{ secrets.jina_auth_token }}
          extended_github_token: ${{ secrets.extended_github_token }}

  regression_test:
    if: ${{ inputs.actions == 'all' ||  contains(inputs.actions, 'regression_test') }}
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.regression_test.outputs.result }}
    strategy:
      matrix:
        node_version:
          - ${{inputs.node_version}}
        python_version: 
          - ${{inputs.python_version}}
        case_path:
          - success/case1
          - success/case2
          - success/case3
          # - success/case4
          - success/case5
          - success/case6
          - success/case6-2
          - success/case6-3
          - success/case7
          - success/case8
          - success/case9
    env:
      NODE_ENV: testing
      JINA_HUBBLE_REGISTRY: http://localhost:3000
    steps:
      - uses: actions/checkout@v3
      - name: regression_test
        uses: jina-ai/hub-integration/actions/regression-test@main
        id: regression_test
        with:
          python_version: ${{ matrix.python_version }}
          node_version: ${{ matrix.node_version }}
          case_path: ${{ matrix.case_path }}
          extended_github_token: ${{ secrets.extended_github_token }}
          hubble_ref: ${{inputs.hubble_ref}}
          jina_ref: ${{inputs.jina_ref}}
